<a href="https://colab.research.google.com/github/Laisalkk/tugas/blob/main/Tugas_ke_2_EDA_KELOMPOK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import pandas as pd
df = pd.read_csv('/content/penduduk_gender_head.csv')
df.head()

,TAHUN,NAMA PROVINSI,NAMA KABUPATEN/KOTA,NAMA KECAMATAN,NAMA KELURAHAN,LAKI-LAKI WNI,PEREMPUAN WNI,LAKI-LAKI WNA,PEREMPUAN WNA
0,2013,PROVINSI DKI JAKARTA,JAKARTA PUSAT,GAMBIR,GAMBIR,1790,1690,1.0,2.0
1,2013,PROVINSI DKI JAKARTA,JAKARTA PUSAT,GAMBIR,CIDENG,9159,9206,5.0,6.0
2,2013,PROVINSI DKI JAKARTA,JAKARTA PUSAT,GAMBIR,PETOJO UTARA,10811,10436,10.0,8.0
3,2013,PROVINSI DKI JAKARTA,JAKARTA PUSAT,GAMBIR,PETOJO SELATAN,8455,8023,5.0,7.0
4,2013,PROVINSI DKI JAKARTA,JAKARTA PUSAT,GAMBIR,KEBON KELAPA,6300,6078,6.0,10.0

In [18]:
df.groupby('NAMA KECAMATAN').groups.keys()

dict_keys(['CEMPAKA PUTIH', 'GAMBIR', 'JOHAR BARU', 'KEMAYORAN', 'MENTENG', 'SAWAH BESAR', 'SENEN', 'TANAH ABANG'])

In [19]:
#Menggunakan kolom NAMA KECAMATAN untuk nantinya dikelompokkan.
Style = df.groupby('NAMA KECAMATAN')
#Mengelompokkan dengan kategori KEMAYORAN
Style.get_group('KEMAYORAN')

,TAHUN,NAMA PROVINSI,NAMA KABUPATEN/KOTA,NAMA KECAMATAN,NAMA KELURAHAN,LAKI-LAKI WNI,PEREMPUAN WNI,LAKI-LAKI WNA,PEREMPUAN WNA
11,2013,PROVINSI DKI JAKARTA,JAKARTA PUSAT,KEMAYORAN,KEMAYORAN,12365,11932,6.0,8.0
12,2013,PROVINSI DKI JAKARTA,JAKARTA PUSAT,KEMAYORAN,KEBON KOSONG,15933,15665,33.0,25.0
13,2013,PROVINSI DKI JAKARTA,JAKARTA PUSAT,KEMAYORAN,HARAPAN MULIA,13523,13049,2.0,3.0
14,2013,PROVINSI DKI JAKARTA,JAKARTA PUSAT,KEMAYORAN,SERDANG,17284,17020,1.0,1.0
15,2013,PROVINSI DKI JAKARTA,JAKARTA PUSAT,KEMAYORAN,GUNUNG SAHARI SELATAN,11730,11487,13.0,15.0
16,2013,PROVINSI DKI JAKARTA,JAKARTA PUSAT,KEMAYORAN,CEMPAKA BARU,19103,18601,NaN,3.0
17,2013,PROVINSI DKI JAKARTA,JAKARTA PUSAT,KEMAYORAN,SUMUR BATU,13441,13288,20.0,13.0
18,2013,PROVINSI DKI JAKARTA,JAKARTA PUSAT,KEMAYORAN,UTAN PANJANG,17125,16351,4.0,3.0

In [22]:
double_grouping = df.groupby(["NAMA KECAMATAN","NAMA KELURAHAN"])
double_grouping.first()

                                      TAHUN         NAMA PROVINSI  \
NAMA KECAMATAN NAMA KELURAHAN
CEMPAKA PUTIH  CEMPAKA PUTIH BARAT     2013  PROVINSI DKI JAKARTA
               CEMPAKA PUTIH TIMUR     2013  PROVINSI DKI JAKARTA
               RAWASARI                2013  PROVINSI DKI JAKARTA
GAMBIR         CIDENG                  2013  PROVINSI DKI JAKARTA
               DURI PULO               2013  PROVINSI DKI JAKARTA
               GAMBIR                  2013  PROVINSI DKI JAKARTA
               KEBON KELAPA            2013  PROVINSI DKI JAKARTA
               PETOJO SELATAN          2013  PROVINSI DKI JAKARTA
               PETOJO UTARA            2013  PROVINSI DKI JAKARTA
JOHAR BARU     GALUR                   2013  PROVINSI DKI JAKARTA
               JOHAR BARU              2013  PROVINSI DKI JAKARTA
               KAMPUNG RAWA            2013  PROVINSI DKI JAKARTA
               TANAH TINGGI            2013  PROVINSI DKI JAKARTA
KEMAYORAN      CEMPAKA BARU            2013  PROVINSI DKI JAKARTA
               GUNUNG SAHARI SELATAN   2013  PROVINSI DKI JAKARTA
               HARAPAN MULIA           2013  PROVINSI DKI JAKARTA
               KEBON KOSONG            2013  PROVINSI DKI JAKARTA
               KEMAYORAN               2013  PROVINSI DKI JAKARTA
               SERDANG                 2013  PROVINSI DKI JAKARTA
               SUMUR BATU              2013  PROVINSI DKI JAKARTA
               UTAN PANJANG            2013  PROVINSI DKI JAKARTA
MENTENG        CIKINI                  2013  PROVINSI DKI JAKARTA
               GONDANGDIA              2013  PROVINSI DKI JAKARTA
               KEBON SIRIH             2013  PROVINSI DKI JAKARTA
               MENTENG                 2013  PROVINSI DKI JAKARTA
               PEGANGSAAN              2013  PROVINSI DKI JAKARTA
SAWAH BESAR    GUNUNG SAHARI UTARA     2013  PROVINSI DKI JAKARTA
               KARANG ANYAR            2013  PROVINSI DKI JAKARTA
               KARTINI                 2013  PROVINSI DKI JAKARTA
               MANGGA DUA SELATAN      2013  PROVINSI DKI JAKARTA
               PASAR BARU              2013  PROVINSI DKI JAKARTA
SENEN          BUNGUR                  2013  PROVINSI DKI JAKARTA
               KENARI                  2013  PROVINSI DKI JAKARTA
               KRAMAT                  2013  PROVINSI DKI JAKARTA
               KWITANG                 2013  PROVINSI DKI JAKARTA
               PASEBAN                 2013  PROVINSI DKI JAKARTA
               SENEN                   2013  PROVINSI DKI JAKARTA
TANAH ABANG    BENDUNGAN HILIR         2013  PROVINSI DKI JAKARTA
               GELORA                  2013  PROVINSI DKI JAKARTA
               KAMPUNG BALI            2013  PROVINSI DKI JAKARTA
               KARET TENGSIN           2013  PROVINSI DKI JAKARTA
               KEBON KACANG            2013  PROVINSI DKI JAKARTA
               KEBON MELATI            2013  PROVINSI DKI JAKARTA
               PETAMBURAN              2013  PROVINSI DKI JAKARTA

                                     NAMA KABUPATEN/KOTA  LAKI-LAKI WNI  \
NAMA KECAMATAN NAMA KELURAHAN
CEMPAKA PUTIH  CEMPAKA PUTIH BARAT         JAKARTA PUSAT          20029
               CEMPAKA PUTIH TIMUR         JAKARTA PUSAT          13630
               RAWASARI                    JAKARTA PUSAT          12462
GAMBIR         CIDENG                      JAKARTA PUSAT           9159
               DURI PULO                   JAKARTA PUSAT          13056
               GAMBIR                      JAKARTA PUSAT           1790
               KEBON KELAPA                JAKARTA PUSAT           6300
               PETOJO SELATAN              JAKARTA PUSAT           8455
               PETOJO UTARA                JAKARTA PUSAT          10811
JOHAR BARU     GALUR                       JAKARTA PUSAT          11077
               JOHAR BARU                  JAKARTA PUSAT          21016
               KAMPUNG RAWA                JAKARTA PUSAT          13337
               TANAH TINGGI                JAKARTA PUSAT          22680
KEMAYORAN      CEMPAKA BARU                JAKARTA PUSAT          19103
               GUNUNG SAHARI SELATAN       JAKARTA PUSAT          11730
               HARAPAN MULIA               JAKARTA PUSAT          13523
               KEBON KOSONG                JAKARTA PUSAT          15933
               KEMAYORAN                   JAKARTA PUSAT          12365
               SERDANG                     JAKARTA PUSAT          17284
               SUMUR BATU                  JAKARTA PUSAT          13441
               UTAN PANJANG                JAKARTA PUSAT          17125
MENTENG        CIKINI                      JAKARTA PUSAT           4825
               GONDANGDIA                  JAKARTA PUSAT           2196
               KEBON SIRIH                 JAKARTA PUSAT           7976
               MENTENG                     JAKARTA PUSAT          14576
               PEGANGSAAN                  JAKARTA PUSAT          13392
SAWAH BESAR    GUNUNG SAHARI UTARA         JAKARTA PUSAT           9734
               KARANG ANYAR                JAKARTA PUSAT          16327
               KARTINI                     JAKARTA PUSAT          13610
               MANGGA DUA SELATAN          JAKARTA PUSAT          17269
               PASAR BARU                  JAKARTA PUSAT           7557
SENEN          BUNGUR                      JAKARTA PUSAT          11200
               KENARI                      JAKARTA PUSAT           5445
               KRAMAT                      JAKARTA PUSAT          17482
               KWITANG                     JAKARTA PUSAT           9176
               PASEBAN                     JAKARTA PUSAT          13787
               SENEN                       JAKARTA PUSAT           4236
TANAH ABANG    BENDUNGAN HILIR             JAKARTA PUSAT          12713
               GELORA                      JAKARTA PUSAT           1865
               KAMPUNG BALI                JAKARTA PUSAT           7348
               KARET TENGSIN               JAKARTA PUSAT          11002
               KEBON KACANG                JAKARTA PUSAT          12873
               KEBON MELATI                JAKARTA PUSAT          19826
               PETAMBURAN                  JAKARTA PUSAT          20112

                                      PEREMPUAN WNI  LAKI-LAKI WNA  \
NAMA KECAMATAN NAMA KELURAHAN
CEMPAKA PUTIH  CEMPAKA PUTIH BARAT            19681           12.0
               CEMPAKA PUTIH TIMUR            13686           24.0
               RAWASARI                       12465            1.0
GAMBIR         CIDENG                          9206            5.0
               DURI PULO                      12588            2.0
               GAMBIR                          1690            1.0
               KEBON KELAPA                    6078            6.0
               PETOJO SELATAN                  8023            5.0
               PETOJO UTARA                   10436           10.0
JOHAR BARU     GALUR                          10259            NaN
               JOHAR BARU                     20953            2.0
               KAMPUNG RAWA                   12499            1.0
               TANAH TINGGI                   21450            NaN
KEMAYORAN      CEMPAKA BARU                   18601            NaN
               GUNUNG SAHARI SELATAN          11487           13.0
               HARAPAN MULIA                  13049            2.0
               KEBON KOSONG                   15665           33.0
               KEMAYORAN                      11932            6.0
               SERDANG                        17020            1.0
               SUMUR BATU                     13288           20.0
               UTAN PANJANG                   16351            4.0
MENTENG        CIKINI                          4772            5.0
               GONDANGDIA                      2443           11.0
               KEBON SIRIH                     7439            2.0
               MENTENG                        14610            7.0
               PEGANGSAAN                     13214            2.0
SAWAH BESAR    GUNUNG SAHARI UTARA             9889           15.0
               KARANG ANYAR                   15859            4.0
               KARTINI                        13808            3.0
               MANGGA DUA SELATAN             16458           42.0
               PASAR BARU                      7552           34.0
SENEN          BUNGUR                         10849            4.0
               KENARI                          5252            2.0
               KRAMAT                         16331            2.0
               KWITANG                         9148            1.0
               PASEBAN                        13477            NaN
               SENEN                           3975           10.0
TANAH ABANG    BENDUNGAN HILIR                12582           11.0
               GELORA                          1883            6.0
               KAMPUNG BALI                    7205            3.0
               KARET TENGSIN                  10271           10.0
               KEBON KACANG                   12357            3.0
               KEBON MELATI                   18672            8.0
               PETAMBURAN                     18794           17.0

                                      PEREMPUAN WNA
NAMA KECAMATAN NAMA KELURAHAN
CEMPAKA PUTIH  CEMPAKA PUTIH BARAT              2.0
               CEMPAKA PUTIH TIMUR             24.0
               RAWASARI                         3.0
GAMBIR         CIDENG                           6.0
               DURI PULO                        6.0
               GAMBIR                           2.0
               KEBON KELAPA                    10.0
               PETOJO SELATAN                   7.0
               PETOJO UTARA                     8.0
JOHAR BARU     GALUR                            NaN
               JOHAR BARU                       NaN
               KAMPUNG RAWA                     NaN
               TANAH TINGGI                     NaN
KEMAYORAN      CEMPAKA BARU                     3.0
               GUNUNG SAHARI SELATAN           15.0
               HARAPAN MULIA                    3.0
               KEBON KOSONG                    25.0
               KEMAYORAN                        8.0
               SERDANG                          1.0
               SUMUR BATU                      13.0
               UTAN PANJANG                     3.0
MENTENG        CIKINI                           1.0
               GONDANGDIA                      13.0
               KEBON SIRIH                      2.0
               MENTENG                         10.0
               PEGANGSAAN                       NaN
SAWAH BESAR    GUNUNG SAHARI UTARA             30.0
               KARANG ANYAR                     2.0
               KARTINI                          3.0
               MANGGA DUA SELATAN              33.0
               PASAR BARU                      55.0
SENEN          BUNGUR                           3.0
               KENARI                           NaN
               KRAMAT                           2.0
               KWITANG                          1.0
               PASEBAN                          NaN
               SENEN                            7.0
TANAH ABANG    BENDUNGAN HILIR                  2.0
               GELORA                           2.0
               KAMPUNG BALI                     1.0
               KARET TENGSIN                    3.0
               KEBON KACANG                     4.0
               KEBON MELATI                     4.0
               PETAMBURAN                      13.0

In [21]:
#max() will print the maximum entry of each group
Style['LAKI-LAKI WNI'].max()
#min() will print the minimum entry of each group
Style['LAKI-LAKI WNI'].min()

NAMA KECAMATAN
CEMPAKA PUTIH    12462
GAMBIR            1790
JOHAR BARU       11077
KEMAYORAN        11730
MENTENG           2196
SAWAH BESAR       7557
SENEN             4236
TANAH ABANG       1865
Name: LAKI-LAKI WNI, dtype: int64

In [24]:
#mean() will print mean of numerical column in each group
Style.mean(numeric_only=True)

,TAHUN,LAKI-LAKI WNI,PEREMPUAN WNI,LAKI-LAKI WNA,PEREMPUAN WNA
NAMA KECAMATAN,,,,,
CEMPAKA PUTIH,2013.0,15373.666667,15277.333333,12.333333,9.666667
GAMBIR,2013.0,8261.833333,8003.500000,4.833333,6.500000
JOHAR BARU,2013.0,17027.500000,16290.250000,1.500000,NaN
KEMAYORAN,2013.0,15063.000000,14674.125000,11.285714,8.875000
MENTENG,2013.0,8593.000000,8495.600000,5.400000,6.500000
SAWAH BESAR,2013.0,12899.400000,12713.200000,19.600000,24.600000
SENEN,2013.0,10221.000000,9838.666667,3.800000,3.250000
TANAH ABANG,2013.0,12248.428571,11680.571429,8.285714,4.142857

In [25]:
#mendapatkan rata-rata setiap kolom dari gaya grup tertentu
Style.get_group("GAMBIR").mean(numeric_only=True)

TAHUN            2013.000000
LAKI-LAKI WNI    8261.833333
PEREMPUAN WNI    8003.500000
LAKI-LAKI WNA       4.833333
PEREMPUAN WNA       6.500000
dtype: float64

In [26]:
#mendapatkan jumlah symboling/rekaman dalam setiap grup
Style['TAHUN'].count()

NAMA KECAMATAN
CEMPAKA PUTIH    3
GAMBIR           6
JOHAR BARU       4
KEMAYORAN        8
MENTENG          5
SAWAH BESAR      5
SENEN            6
TANAH ABANG      7
Name: TAHUN, dtype: int64

In [29]:
import numpy as np
data = pd.read_csv('/content/penduduk_gender_head.csv')
pivot_table = pd.pivot_table(data, values=["LAKI-LAKI WNI", "PEREMPUAN WNI"], index=["NAMA KECAMATAN", "NAMA KABUPATEN/KOTA",], columns= "NAMA PROVINSI", aggfunc=np.sum)
pivot_table

<ipython-input-29-c4659dab330a>:3: FutureWarning: The provided callable <function sum at 0x7d75e39f4670> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  pivot_table = pd.pivot_table(data, values=["LAKI-LAKI WNI", "PEREMPUAN WNI"], index=["NAMA KECAMATAN", "NAMA KABUPATEN/KOTA",], columns= "NAMA PROVINSI", aggfunc=np.sum)

                                          LAKI-LAKI WNI        PEREMPUAN WNI
NAMA PROVINSI                      PROVINSI DKI JAKARTA PROVINSI DKI JAKARTA
NAMA KECAMATAN NAMA KABUPATEN/KOTA
CEMPAKA PUTIH  JAKARTA PUSAT                      46121                45832
GAMBIR         JAKARTA PUSAT                      49571                48021
JOHAR BARU     JAKARTA PUSAT                      68110                65161
KEMAYORAN      JAKARTA PUSAT                     120504               117393
MENTENG        JAKARTA PUSAT                      42965                42478
SAWAH BESAR    JAKARTA PUSAT                      64497                63566
SENEN          JAKARTA PUSAT                      61326                59032
TANAH ABANG    JAKARTA PUSAT                      85739                81764

In [30]:
table = pd.pivot_table(
    data,
    values=["LAKI-LAKI WNI", "PEREMPUAN WNI", "LAKI-LAKI WNA"],
    index=["NAMA KECAMATAN", "NAMA KABUPATEN/KOTA"],
    aggfunc={
        "LAKI-LAKI WNI": np.mean,
        "PEREMPUAN WNI": [min, max],
        "LAKI-LAKI WNA": [min, max]
    },
    fill_value=0
)
table

<ipython-input-30-8c6e7ae3ba73>:1: FutureWarning: The provided callable <function mean at 0x7d75e39f55a0> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  table = pd.pivot_table(
<ipython-input-30-8c6e7ae3ba73>:1: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  table = pd.pivot_table(
<ipython-input-30-8c6e7ae3ba73>:1: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  table = pd.pivot_table(

                                   LAKI-LAKI WNA      LAKI-LAKI WNI  \
                                             max  min          mean
NAMA KECAMATAN NAMA KABUPATEN/KOTA
CEMPAKA PUTIH  JAKARTA PUSAT                24.0  1.0  15373.666667
GAMBIR         JAKARTA PUSAT                10.0  1.0   8261.833333
JOHAR BARU     JAKARTA PUSAT                 2.0  1.0  17027.500000
KEMAYORAN      JAKARTA PUSAT                33.0  1.0  15063.000000
MENTENG        JAKARTA PUSAT                11.0  2.0   8593.000000
SAWAH BESAR    JAKARTA PUSAT                42.0  3.0  12899.400000
SENEN          JAKARTA PUSAT                10.0  1.0  10221.000000
TANAH ABANG    JAKARTA PUSAT                17.0  3.0  12248.428571

                                   PEREMPUAN WNI
                                             max    min
NAMA KECAMATAN NAMA KABUPATEN/KOTA
CEMPAKA PUTIH  JAKARTA PUSAT               19681  12465
GAMBIR         JAKARTA PUSAT               12588   1690
JOHAR BARU     JAKARTA PUSAT               21450  10259
KEMAYORAN      JAKARTA PUSAT               18601  11487
MENTENG        JAKARTA PUSAT               14610   2443
SAWAH BESAR    JAKARTA PUSAT               16458   7552
SENEN          JAKARTA PUSAT               16331   3975
TANAH ABANG    JAKARTA PUSAT               18794   1883

In [31]:
cross_tab = pd.crosstab(data['NAMA KECAMATAN'], data['NAMA KELURAHAN'])
cross_tab

NAMA KELURAHAN,BENDUNGAN HILIR,BUNGUR,CEMPAKA BARU,CEMPAKA PUTIH BARAT,CEMPAKA PUTIH TIMUR,CIDENG,CIKINI,DURI PULO,GALUR,GAMBIR,...,PEGANGSAAN,PETAMBURAN,PETOJO SELATAN,PETOJO UTARA,RAWASARI,SENEN,SERDANG,SUMUR BATU,TANAH TINGGI,UTAN PANJANG
NAMA KECAMATAN,,,,,,,,,,,,,,,,,,,,,
CEMPAKA PUTIH,0,0,0,1,1,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
GAMBIR,0,0,0,0,0,1,0,1,0,1,...,0,0,1,1,0,0,0,0,0,0
JOHAR BARU,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
KEMAYORAN,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,1,0,1
MENTENG,0,0,0,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,0,0
SAWAH BESAR,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
SENEN,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
TANAH ABANG,1,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0

In [32]:
cross_tab_total = pd.crosstab(data['NAMA KECAMATAN'], data['NAMA KELURAHAN'], margins=True, margins_name='Total')
cross_tab_total

NAMA KELURAHAN,BENDUNGAN HILIR,BUNGUR,CEMPAKA BARU,CEMPAKA PUTIH BARAT,CEMPAKA PUTIH TIMUR,CIDENG,CIKINI,DURI PULO,GALUR,GAMBIR,...,PETAMBURAN,PETOJO SELATAN,PETOJO UTARA,RAWASARI,SENEN,SERDANG,SUMUR BATU,TANAH TINGGI,UTAN PANJANG,Total
NAMA KECAMATAN,,,,,,,,,,,,,,,,,,,,,
CEMPAKA PUTIH,0,0,0,1,1,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,3
GAMBIR,0,0,0,0,0,1,0,1,0,1,...,0,1,1,0,0,0,0,0,0,6
JOHAR BARU,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,1,0,4
KEMAYORAN,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1,0,1,8
MENTENG,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,5
SAWAH BESAR,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,5
SENEN,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,6
TANAH ABANG,1,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,7
Total,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,44

In [33]:
crosstab_table = pd.crosstab(
data["NAMA KECAMATAN"],
data["NAMA KELURAHAN"],
values=data["LAKI-LAKI WNI"],
aggfunc="sum",
)
crosstab_table

NAMA KELURAHAN,BENDUNGAN HILIR,BUNGUR,CEMPAKA BARU,CEMPAKA PUTIH BARAT,CEMPAKA PUTIH TIMUR,CIDENG,CIKINI,DURI PULO,GALUR,GAMBIR,...,PEGANGSAAN,PETAMBURAN,PETOJO SELATAN,PETOJO UTARA,RAWASARI,SENEN,SERDANG,SUMUR BATU,TANAH TINGGI,UTAN PANJANG
NAMA KECAMATAN,,,,,,,,,,,,,,,,,,,,,
CEMPAKA PUTIH,NaN,NaN,NaN,20029.0,13630.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,12462.0,NaN,NaN,NaN,NaN,NaN
GAMBIR,NaN,NaN,NaN,NaN,NaN,9159.0,NaN,13056.0,NaN,1790.0,...,NaN,NaN,8455.0,10811.0,NaN,NaN,NaN,NaN,NaN,NaN
JOHAR BARU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11077.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22680.0,NaN
KEMAYORAN,NaN,NaN,19103.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,17284.0,13441.0,NaN,17125.0
MENTENG,NaN,NaN,NaN,NaN,NaN,NaN,4825.0,NaN,NaN,NaN,...,13392.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SAWAH BESAR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SENEN,NaN,11200.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,4236.0,NaN,NaN,NaN,NaN
TANAH ABANG,12713.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,20112.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
crosstab_normalized = pd.crosstab(
data["NAMA KECAMATAN"],
data["NAMA KELURAHAN"],
values=data["LAKI-LAKI WNI"],
aggfunc="sum",
normalize=True
)
crosstab_normalized

NAMA KELURAHAN,BENDUNGAN HILIR,BUNGUR,CEMPAKA BARU,CEMPAKA PUTIH BARAT,CEMPAKA PUTIH TIMUR,CIDENG,CIKINI,DURI PULO,GALUR,GAMBIR,...,PEGANGSAAN,PETAMBURAN,PETOJO SELATAN,PETOJO UTARA,RAWASARI,SENEN,SERDANG,SUMUR BATU,TANAH TINGGI,UTAN PANJANG
NAMA KECAMATAN,,,,,,,,,,,,,,,,,,,,,
CEMPAKA PUTIH,0.000000,0.000000,0.000000,0.037171,0.025295,0.000000,0.000000,0.00000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.023128,0.000000,0.000000,0.000000,0.000000,0.000000
GAMBIR,0.000000,0.000000,0.000000,0.000000,0.000000,0.016998,0.000000,0.02423,0.000000,0.003322,...,0.000000,0.000000,0.015691,0.020064,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
JOHAR BARU,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.020557,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.042091,0.000000
KEMAYORAN,0.000000,0.000000,0.035453,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.032077,0.024945,0.000000,0.031782
MENTENG,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.008955,0.00000,0.000000,0.000000,...,0.024854,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
SAWAH BESAR,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
SENEN,0.000000,0.020786,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.007861,0.000000,0.000000,0.000000,0.000000
TANAH ABANG,0.023594,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,...,0.000000,0.037325,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [37]:
# Membaca data
df = pd.read_csv('/content/penduduk_gender_head.csv')

# 1. Mengelompokkan data berdasarkan 'NAMA PROVINSI'
grouped_by_provinsi = df.groupby('NAMA PROVINSI')
# Menghitung rata-rata, minimum, dan maksimum untuk kolom populasi berdasarkan NAMA PROVINSI
statistik_data = grouped_by_provinsi.agg({
'LAKI-LAKI WNI': ['mean', 'min', 'max'],
'PEREMPUAN WNI': ['mean', 'min', 'max']
})
print("\nStatistik Rata-Rata, Minimum, dan Maksimum Populasi Laki-Laki dan Perempuan WNI per Provinsi:")
print(statistik_data)

Statistik Rata-Rata, Minimum, dan Maksimum Populasi Laki-Laki dan Perempuan WNI per Provinsi:
                     LAKI-LAKI WNI              PEREMPUAN WNI
                              mean   min    max          mean   min    max
NAMA PROVINSI
PROVINSI DKI JAKARTA  12246.204545  1790  22680  11891.977273  1690  21450

In [38]:
# Group-wise Aggregation berdasarkan NAMA PROVINSI
grouped_aggregation = df.groupby('NAMA PROVINSI').agg({
'LAKI-LAKI WNI': ['sum', 'min', 'max', 'mean', 'count'],
'PEREMPUAN WNI': ['sum', 'min', 'max', 'mean', 'count'],
'LAKI-LAKI WNA': ['sum', 'min', 'max', 'mean', 'count'],
'PEREMPUAN WNA': ['sum', 'min', 'max', 'mean', 'count']
})

# Menampilkan hasil
print(grouped_aggregation)

                     LAKI-LAKI WNI                                   \
                               sum   min    max          mean count
NAMA PROVINSI
PROVINSI DKI JAKARTA        538833  1790  22680  12246.204545    44

                     PEREMPUAN WNI                                   \
                               sum   min    max          mean count
NAMA PROVINSI
PROVINSI DKI JAKARTA        523247  1690  21450  11891.977273    44

                     LAKI-LAKI WNA                        PEREMPUAN WNA       \
                               sum  min   max  mean count           sum  min
NAMA PROVINSI
PROVINSI DKI JAKARTA         350.0  1.0  42.0  8.75    40         330.0  1.0


                       max      mean count
NAMA PROVINSI
PROVINSI DKI JAKARTA  55.0  8.918919    37

In [39]:
# Menghitung total populasi Laki-Laki WNI dan Perempuan WNI di setiap provinsi
agg_data = grouped_by_provinsi.agg({
'LAKI-LAKI WNI': 'sum',
'PEREMPUAN WNI': 'sum'
}).reset_index()
print("Agregasi Total Populasi Laki-Laki dan Perempuan WNI per Provinsi:")
print(agg_data)

Agregasi Total Populasi Laki-Laki dan Perempuan WNI per Provinsi:
          NAMA PROVINSI  LAKI-LAKI WNI  PEREMPUAN WNI
0  PROVINSI DKI JAKARTA         538833         523247

In [41]:
# Menghitung proporsi Laki-Laki WNI di setiap kelurahan berdasarkan total Laki-Laki WNI di provinsi tersebut
df['Proporsi_LAKI_LAKI_WNI'] = grouped_by_provinsi['LAKI-LAKI WNI'].transform(lambda x: x / x.sum())
df['Proporsi_PEREMPUAN_WNI'] = grouped_by_provinsi['PEREMPUAN WNI'].transform(lambda x: x / x.sum())

# Menampilkan data dengan kolom proporsi baru
print("\nData dengan Kolom Proporsi Laki-Laki dan Perempuan WNI per Kelurahan dalam Setiap Provinsi:")
print(df[['NAMA PROVINSI', 'NAMA KELURAHAN', 'LAKI-LAKI WNI', 'Proporsi_LAKI_LAKI_WNI', 'PEREMPUAN WNI', 'Proporsi_PEREMPUAN_WNI']])

Data dengan Kolom Proporsi Laki-Laki dan Perempuan WNI per Kelurahan dalam Setiap Provinsi:
           NAMA PROVINSI         NAMA KELURAHAN  LAKI-LAKI WNI  \
0   PROVINSI DKI JAKARTA                 GAMBIR           1790
1   PROVINSI DKI JAKARTA                 CIDENG           9159
2   PROVINSI DKI JAKARTA           PETOJO UTARA          10811
3   PROVINSI DKI JAKARTA         PETOJO SELATAN           8455
4   PROVINSI DKI JAKARTA           KEBON KELAPA           6300
5   PROVINSI DKI JAKARTA              DURI PULO          13056
6   PROVINSI DKI JAKARTA             PASAR BARU           7557
7   PROVINSI DKI JAKARTA           KARANG ANYAR          16327
8   PROVINSI DKI JAKARTA                KARTINI          13610
9   PROVINSI DKI JAKARTA    GUNUNG SAHARI UTARA           9734
10  PROVINSI DKI JAKARTA     MANGGA DUA SELATAN          17269
11  PROVINSI DKI JAKARTA              KEMAYORAN          12365
12  PROVINSI DKI JAKARTA           KEBON KOSONG          15933
13  PROVINSI DKI JAKARTA          HARAPAN MULIA          13523
14  PROVINSI DKI JAKARTA                SERDANG          17284
15  PROVINSI DKI JAKARTA  GUNUNG SAHARI SELATAN          11730
16  PROVINSI DKI JAKARTA           CEMPAKA BARU          19103
17  PROVINSI DKI JAKARTA             SUMUR BATU          13441
18  PROVINSI DKI JAKARTA           UTAN PANJANG          17125
19  PROVINSI DKI JAKARTA                  SENEN           4236
20  PROVINSI DKI JAKARTA                 KENARI           5445
21  PROVINSI DKI JAKARTA                PASEBAN          13787
22  PROVINSI DKI JAKARTA                 KRAMAT          17482
23  PROVINSI DKI JAKARTA                KWITANG           9176
24  PROVINSI DKI JAKARTA                 BUNGUR          11200
25  PROVINSI DKI JAKARTA    CEMPAKA PUTIH TIMUR          13630
26  PROVINSI DKI JAKARTA    CEMPAKA PUTIH BARAT          20029
27  PROVINSI DKI JAKARTA               RAWASARI          12462
28  PROVINSI DKI JAKARTA                MENTENG          14576
29  PROVINSI DKI JAKARTA             PEGANGSAAN          13392
30  PROVINSI DKI JAKARTA                 CIKINI           4825
31  PROVINSI DKI JAKARTA             GONDANGDIA           2196
32  PROVINSI DKI JAKARTA            KEBON SIRIH           7976
33  PROVINSI DKI JAKARTA                 GELORA           1865
34  PROVINSI DKI JAKARTA        BENDUNGAN HILIR          12713
35  PROVINSI DKI JAKARTA          KARET TENGSIN          11002
36  PROVINSI DKI JAKARTA             PETAMBURAN          20112
37  PROVINSI DKI JAKARTA           KEBON MELATI          19826
38  PROVINSI DKI JAKARTA           KEBON KACANG          12873
39  PROVINSI DKI JAKARTA           KAMPUNG BALI           7348
40  PROVINSI DKI JAKARTA             JOHAR BARU          21016
41  PROVINSI DKI JAKARTA           KAMPUNG RAWA          13337
42  PROVINSI DKI JAKARTA                  GALUR          11077
43  PROVINSI DKI JAKARTA           TANAH TINGGI          22680

    Proporsi_LAKI_LAKI_WNI  PEREMPUAN WNI  Proporsi_PEREMPUAN_WNI
0                 0.003322           1690                0.003230
1                 0.016998           9206                0.017594
2                 0.020064          10436                0.019945
3                 0.015691           8023                0.015333
4                 0.011692           6078                0.011616
5                 0.024230          12588                0.024057
6                 0.014025           7552                0.014433
7                 0.030301          15859                0.030309
8                 0.025258          13808                0.026389
9                 0.018065           9889                0.018899
10                0.032049          16458                0.031454
11                0.022948          11932                0.022804
12                0.029569          15665                0.029938
13                0.025097          13049                0.024939
14                0.032077          17020                0.032528
15                0.021769          11487                0.021953
16                0.035453          18601                0.035549
17                0.024945          13288                0.025395
18                0.031782          16351                0.031249
19                0.007861           3975                0.007597
20                0.010105           5252                0.010037
21                0.025587          13477                0.025756
22                0.032444          16331                0.031211
23                0.017029           9148                0.017483
24                0.020786          10849                0.020734
25                0.025295          13686                0.026156
26                0.037171          19681                0.037613
27                0.023128          12465                0.023822
28                0.027051          14610                0.027922
29                0.024854          13214                0.025254
30                0.008955           4772                0.009120
31                0.004075           2443                0.004669
32                0.014802           7439                0.014217
33                0.003461           1883                0.003599
34                0.023594          12582                0.024046
35                0.020418          10271                0.019629
36                0.037325          18794                0.035918
37                0.036794          18672                0.035685
38                0.023891          12357                0.023616
39                0.013637           7205                0.013770
40                0.039003          20953                0.040044
41                0.024752          12499                0.023887
42                0.020557          10259                0.019606
43                0.042091          21450                0.040994